general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid multiple instances
    before_sleep_cmd = loginctl lock-session    # lock before hibernate/suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # force monitor on after wake
}

# 1. Lock screen after 5 mins
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 2. Turn off screen after 5.5 mins
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off       # command to turn off
    on-resume = hyprctl dispatch dpms on        # REQUIRED command to wake
}
